#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# serve-nginx.sh — Generate an nginx.conf from the _redirects file and
# serve the built site locally via NGINX.
#
# Usage:
#   ./scripts/serve-nginx.sh              # serve on port 8080 (default)
#   PORT=3000 ./scripts/serve-nginx.sh    # serve on a custom port
#
# Prerequisites:
#   - nginx installed (brew install nginx / apt install nginx)
#   - The site has been built (npm run build)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DIST_DIR="$PROJECT_ROOT/dist"
REDIRECTS_FILE="$DIST_DIR/_redirects"
NGINX_CONF="$PROJECT_ROOT/nginx.conf"
PORT="${PORT:-8080}"

# ── Preflight checks ───────────────────────────────────────────────────────
if ! command -v nginx &>/dev/null; then
  echo "Error: nginx is not installed. Install it first:"
  echo "  macOS:  brew install nginx"
  echo "  Linux:  sudo apt install nginx"
  exit 1
fi

if [ ! -d "$DIST_DIR" ]; then
  echo "Error: dist/ not found. Run 'npm run build' first."
  exit 1
fi

# ── Parse _redirects → NGINX directives ────────────────────────────────────
generate_redirect_rules() {
  if [ ! -f "$REDIRECTS_FILE" ]; then
    echo "  # No _redirects file found"
    return
  fi

  while IFS= read -r line || [ -n "$line" ]; do
    # Skip empty lines and comments
    line="$(echo "$line" | sed 's/#.*//' | xargs)"
    [ -z "$line" ] && continue

    # Parse: <source> <destination> <status>
    source_path="$(echo "$line" | awk '{print $1}')"
    dest_path="$(echo "$line" | awk '{print $2}')"
    status_code="$(echo "$line" | awk '{print $3}')"

    [ -z "$source_path" ] || [ -z "$dest_path" ] && continue

    # Convert Netlify-style patterns to NGINX
    if [ "$source_path" = "/*" ]; then
      # Catch-all SPA fallback
      if [ "$status_code" = "200" ]; then
        echo "  # SPA fallback (from _redirects: $line)"
        echo "  location / {"
        echo "    try_files \$uri \$uri/ /index.html;"
        echo "  }"
      else
        echo "  # Catch-all redirect (from _redirects: $line)"
        echo "  location / {"
        echo "    return ${status_code:-301} ${dest_path};"
        echo "  }"
      fi
    elif echo "$source_path" | grep -q '\*$'; then
      # Wildcard path like /old/*
      prefix="${source_path%\*}"
      if [ "$status_code" = "200" ]; then
        echo "  # Rewrite (from _redirects: $line)"
        echo "  location ${prefix} {"
        echo "    try_files \$uri ${dest_path};"
        echo "  }"
      else
        echo "  # Redirect (from _redirects: $line)"
        echo "  location ${prefix} {"
        echo "    return ${status_code:-301} ${dest_path};"
        echo "  }"
      fi
    else
      # Exact path
      if [ "$status_code" = "200" ]; then
        echo "  # Rewrite (from _redirects: $line)"
        echo "  location = ${source_path} {"
        echo "    try_files ${dest_path} =404;"
        echo "  }"
      else
        echo "  # Redirect (from _redirects: $line)"
        echo "  location = ${source_path} {"
        echo "    return ${status_code:-301} ${dest_path};"
        echo "  }"
      fi
    fi
    echo ""
  done < "$REDIRECTS_FILE"
}

# ── Generate nginx.conf ───────────────────────────────────────────────────
cat > "$NGINX_CONF" <<NGINX_EOF
# Auto-generated by serve-nginx.sh — do not edit directly.
# Regenerate with: ./scripts/serve-nginx.sh

worker_processes 1;
daemon off;
pid $PROJECT_ROOT/nginx.pid;

events {
  worker_connections 128;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  sendfile    on;
  tcp_nopush  on;

  # Logging to stdout/stderr for easy debugging
  access_log /dev/stdout;
  error_log  /dev/stderr warn;

  # Gzip
  gzip on;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;
  gzip_min_length 256;

  server {
    listen $PORT;
    server_name localhost;
    root $DIST_DIR;
    index index.html;

    # Cache static assets aggressively (Vite hashes filenames)
    location /assets/ {
      expires 1y;
      add_header Cache-Control "public, immutable";
    }

    # Uploaded content
    location /uploads/ {
      expires 7d;
      add_header Cache-Control "public";
    }

    # Rules generated from _redirects
$(generate_redirect_rules)
  }
}
NGINX_EOF

echo "Generated $NGINX_CONF"
echo "Serving dist/ on http://localhost:$PORT (Ctrl+C to stop)"
echo ""

# ── Start NGINX in foreground ─────────────────────────────────────────────
exec nginx -c "$NGINX_CONF"
